#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-bokeh
Version  : 3.2.1
Release  : 67
URL      : https://files.pythonhosted.org/packages/cf/7f/ceb7f3949bd24b8df3ad1305f8a863ef4f862eb35fe8c83bd3b6415dbf00/bokeh-3.2.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/cf/7f/ceb7f3949bd24b8df3ad1305f8a863ef4f862eb35fe8c83bd3b6415dbf00/bokeh-3.2.1.tar.gz
Summary  : Interactive plots and applications in the browser from Python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-bokeh-bin = %{version}-%{release}
Requires: pypi-bokeh-license = %{version}-%{release}
Requires: pypi-bokeh-python = %{version}-%{release}
Requires: pypi-bokeh-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(colorama)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_git_versioning)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<picture>
<source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/bokeh/pm/main/assets/logos/SVG/bokeh-logo-white-text-no-padding.svg">
<img src="https://raw.githubusercontent.com/bokeh/pm/main/assets/logos/SVG/bokeh-logo-black-text-no-padding.svg" alt="Bokeh logo -- text is white in dark theme and black in light theme" height=60/>
</picture>

%package bin
Summary: bin components for the pypi-bokeh package.
Group: Binaries
Requires: pypi-bokeh-license = %{version}-%{release}

%description bin
bin components for the pypi-bokeh package.


%package license
Summary: license components for the pypi-bokeh package.
Group: Default

%description license
license components for the pypi-bokeh package.


%package python
Summary: python components for the pypi-bokeh package.
Group: Default
Requires: pypi-bokeh-python3 = %{version}-%{release}

%description python
python components for the pypi-bokeh package.


%package python3
Summary: python3 components for the pypi-bokeh package.
Group: Default
Requires: python3-core
Provides: pypi(bokeh)
Requires: pypi(contourpy)
Requires: pypi(jinja2)
Requires: pypi(numpy)
Requires: pypi(packaging)
Requires: pypi(pandas)
Requires: pypi(pillow)
Requires: pypi(pyyaml)
Requires: pypi(tornado)
Requires: pypi(xyzservices)

%description python3
python3 components for the pypi-bokeh package.


%prep
%setup -q -n bokeh-3.2.1
cd %{_builddir}/bokeh-3.2.1
pushd ..
cp -a bokeh-3.2.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1689867690
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-bokeh
cp %{_builddir}/bokeh-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-bokeh/8d740670d4c0d9b1a6c7ef9fd0ecdf6cf92d36c7 || :
cp %{_builddir}/bokeh-%{version}/src/bokeh/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-bokeh/8d740670d4c0d9b1a6c7ef9fd0ecdf6cf92d36c7 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bokeh

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-bokeh/8d740670d4c0d9b1a6c7ef9fd0ecdf6cf92d36c7

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
