#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-bokeh
Version  : 2.0.0
Release  : 48
URL      : https://files.pythonhosted.org/packages/e0/a7/875aad223b211951a043bf7b0eddcecb8b2afd5131c08945ff07ac968c7f/bokeh-2.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/e0/a7/875aad223b211951a043bf7b0eddcecb8b2afd5131c08945ff07ac968c7f/bokeh-2.0.0.tar.gz
Summary  : Interactive plots and applications in the browser from Python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-bokeh-bin = %{version}-%{release}
Requires: pypi-bokeh-license = %{version}-%{release}
Requires: pypi-bokeh-python = %{version}-%{release}
Requires: pypi-bokeh-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(jinja2)
BuildRequires : pypi(numpy)
BuildRequires : pypi(packaging)
BuildRequires : pypi(pillow)
BuildRequires : pypi(python_dateutil)
BuildRequires : pypi(pyyaml)
BuildRequires : pypi(tornado)
BuildRequires : pypi(typing_extensions)

%description
<a href="https://bokeh.org">
<img src="https://static.bokeh.org/logos/logotype.svg" height="60" alt="Bokeh logotype" />
</a>

%package bin
Summary: bin components for the pypi-bokeh package.
Group: Binaries
Requires: pypi-bokeh-license = %{version}-%{release}

%description bin
bin components for the pypi-bokeh package.


%package license
Summary: license components for the pypi-bokeh package.
Group: Default

%description license
license components for the pypi-bokeh package.


%package python
Summary: python components for the pypi-bokeh package.
Group: Default
Requires: pypi-bokeh-python3 = %{version}-%{release}

%description python
python components for the pypi-bokeh package.


%package python3
Summary: python3 components for the pypi-bokeh package.
Group: Default
Requires: python3-core
Provides: pypi(bokeh)
Requires: pypi(jinja2)
Requires: pypi(numpy)
Requires: pypi(packaging)
Requires: pypi(pillow)
Requires: pypi(python_dateutil)
Requires: pypi(pyyaml)
Requires: pypi(tornado)
Requires: pypi(typing_extensions)

%description python3
python3 components for the pypi-bokeh package.


%prep
%setup -q -n bokeh-2.0.0
cd %{_builddir}/bokeh-2.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641508334
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-bokeh
cp %{_builddir}/bokeh-2.0.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-bokeh/19f653e42c734907a4384cd22d54edadf6f0c14e
cp %{_builddir}/bokeh-2.0.0/bokeh/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-bokeh/19f653e42c734907a4384cd22d54edadf6f0c14e
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bokeh

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-bokeh/19f653e42c734907a4384cd22d54edadf6f0c14e

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
